import type { Plugin, ViteDevServer } from 'vite';
import {
  cpSync,
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  rmSync,
  statSync,
} from 'node:fs';
import { join, relative, resolve } from 'node:path';

/** shopify-lit writes these into dist/snippets — never prune them from sync. */
const AUTO_GEN_MARKER = 'AUTO-GENERATED from';

const THEME_DIRS = [
  'layout',
  'sections',
  'snippets',
  'templates',
  'config',
  'locales',
  'blocks',
  'assets',
] as const;

const THEME_ROOT_FILES = ['.shopifyignore', '.theme-check.yml'] as const;

export type ThemeSyncOptions = {
  /** Theme source (Liquid, config, static assets). Default: `src` */
  srcDir?: string;
  /** Built theme root for Shopify CLI. Default: `dist` */
  outDir?: string;
  /**
   * Files under outDir/snippets that are generated by other plugins and should
   * not be deleted when syncing (they may be rewritten after sync).
   */
  preserveSnippetNames?: string[];
};

/**
 * Mirror `src/{layout,sections,…}` → `dist/` so Shopify CLI (`--path dist`)
 * sees a complete theme. Watches in dev; runs once on build.
 */
export function themeSync(options: ThemeSyncOptions = {}): Plugin {
  const srcDir = options.srcDir ?? 'src';
  const outDir = options.outDir ?? 'dist';
  const preserve = new Set(
    options.preserveSnippetNames ?? ['vite.liquid', 'importmap.liquid'],
  );

  let root = process.cwd();
  let server: ViteDevServer | undefined;

  const absSrc = () => resolve(root, srcDir);
  const absOut = () => resolve(root, outDir);

  const syncAll = (reason?: string) => {
    const fromRoot = absSrc();
    const toRoot = absOut();
    if (!existsSync(fromRoot)) return;

    mkdirSync(toRoot, { recursive: true });

    for (const dir of THEME_DIRS) {
      const from = join(fromRoot, dir);
      const to = join(toRoot, dir);
      if (!existsSync(from)) {
        mkdirSync(to, { recursive: true });
        continue;
      }

      mkdirSync(to, { recursive: true });

      // Remove out files that no longer exist in src (except preserved / built assets)
      if (dir !== 'assets') {
        pruneMissing(from, to, dir === 'snippets' ? preserve : undefined);
      }

      cpSync(from, to, {
        recursive: true,
        force: true,
        filter: (src) => {
          if (dir !== 'snippets') return true;
          const base = src.split(/[/\\]/).pop() ?? '';
          // Generated by Vite plugins into dist — never copy stale copies from src
          if (preserve.has(base)) return false;
          return true;
        },
      });
    }

    for (const file of THEME_ROOT_FILES) {
      const from = join(fromRoot, file);
      if (!existsSync(from)) continue;
      cpSync(from, join(toRoot, file), { force: true });
    }

    if (server && reason) {
      server.config.logger.info(`[theme-sync] ${reason}`, { timestamp: true });
    }
  };

  return {
    name: 'theme-sync',
    configResolved(config) {
      root = config.root;
    },
    buildStart() {
      syncAll('buildStart');
    },
    configureServer(devServer) {
      server = devServer;
      syncAll('configureServer');

      const fromRoot = absSrc();
      server.watcher.add(fromRoot);

      let timer: ReturnType<typeof setTimeout> | undefined;
      const schedule = (file: string) => {
        clearTimeout(timer);
        timer = setTimeout(() => {
          const rel = relative(fromRoot, file);
          // Only sync theme dirs, not frontend TS (Vite handles those)
          const top = rel.split(/[/\\]/)[0];
          if (!(THEME_DIRS as readonly string[]).includes(top)) return;
          syncAll(rel);
        }, 40);
      };

      server.watcher.on('change', schedule);
      server.watcher.on('add', schedule);
      server.watcher.on('unlink', schedule);
    },
  };
}

function isAutoGeneratedLiquid(filePath: string): boolean {
  if (!filePath.endsWith('.liquid')) return false;
  try {
    return readFileSync(filePath, 'utf8')
      .slice(0, 200)
      .includes(AUTO_GEN_MARKER);
  } catch {
    return false;
  }
}

function pruneMissing(
  fromDir: string,
  toDir: string,
  preserveNames?: Set<string>,
): void {
  if (!existsSync(toDir)) return;
  for (const name of readdirSync(toDir)) {
    if (preserveNames?.has(name)) continue;
    const fromPath = join(fromDir, name);
    const toPath = join(toDir, name);
    if (!existsSync(fromPath)) {
      // shopify-lit owns these in dist/ — themeSync must not wipe them
      if (isAutoGeneratedLiquid(toPath)) continue;
      rmSync(toPath, { recursive: true, force: true });
      continue;
    }
    if (statSync(toPath).isDirectory() && statSync(fromPath).isDirectory()) {
      pruneMissing(fromPath, toPath, preserveNames);
    }
  }
}

export default themeSync;
